[package]
name = "toy-os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = { path = "../bootloader" }
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[workspace]
members = ["kernel"]